/*
 * timer.h
 *
 *  Created on: 16.03.2015
 *      Author: Marko Petrovic
 */

#define NUMBER_OF_TIMERS	8
#define DMTIMER_TCLR_START	(0x01)
#define DMTIMER_TCLR_STOP	(0xFFFFFFFE)

#define DMTIMER_WRITE_POST_TCRR DMTIMER_TWPS_W_PEND_TCLR
#define DMTIMER_WRITE_POST_TCLR	DMTIMER_TWPS_W_PEND_TCLR
#define DMTIMER_IS_RESET_DONE (DMTIMER_TIOCP_CFG_SOFTRESET_DONE)


typedef enum {TIMER0, TIMER1_MS, TIMER2,
	TIMER3, TIMER4, TIMER5, TIMER6, TIMER7
	} Timer_t;

