/*
 * hw_cm_dpll.h
 *
 *  Created on: 25.03.2015
 *      Author: Marko Petrovic
 */

/*************************************************************************\
 * Registers Definition
\*************************************************************************/

#define CM_DPLL_CLKSEL_TIMER7_CLK   		(0x4)
#define CM_DPLL_CLKSEL_TIMER2_CLK   		(0x8)
#define CM_DPLL_CLKSEL_TIMER3_CLK   		(0xc)
#define CM_DPLL_CLKSEL_TIMER4_CLK   		(0x10)
#define CM_DPLL_CM_MAC_CLKSEL   			(0x14)
#define CM_DPLL_CLKSEL_TIMER5_CLK   		(0x18)
#define CM_DPLL_CLKSEL_TIMER6_CLK   		(0x1c)
#define CM_DPLL_CM_CPTS_RFT_CLKSEL   		(0x20)
#define CM_DPLL_CLKSEL_TIMER1MS_CLK   		(0x28)
#define CM_DPLL_CLKSEL_GFX_FCLK   			(0x2c)
#define CM_DPLL_CLKSEL_ICSS_OCP_CLK   		(0x30)
#define CM_DPLL_CLKSEL_LCDC_PIXEL_CLK   	(0x34)
#define CM_DPLL_CLKSEL_WDT1_CLK   			(0x38)
#define CM_DPLL_CLKSEL_GPIO0_DBCLK   		(0x3c)


// clock settings
#define TIMER_CLK_SELECTION_RANGE			(0x00000003u)
#define TIMER_CLK_SELECT_TCLKIN   			(0x0u)
#define TIMER_CLK_SELECT_M_OSC   			(0x1u)
#define TIMER_CLK_SELECT_32KHZ   			(0x2u)


// CLKSEL_TIMER1MS_CLK
#define TIMER1MS_CLK_SELECTION_RANGE   		(0x00000007u)
#define TIMER1MS_CLK_SELECT_M_OSC   		(0x0u)
#define TIMER1MS_CLK_SELECT_32KHZ   		(0x1u)
#define TIMER1MS_CLK_SELECT_TCLKIN			(0x2u)
#define TIMER1MS_CLK_SELECT_RC32K   		(0x3u)
#define TIMER1MS_CLK_SELECT_32768   		(0x4u)




/* CM_MAC_CLKSEL */
#define CM_DPLL_CM_MAC_CLKSEL_MII_CLK_SEL   (0x00000004u)
#define CM_DPLL_CM_MAC_CLKSEL_MII_CLK_SEL_SHIFT   (0x00000002u)
#define CM_DPLL_CM_MAC_CLKSEL_MII_CLK_SEL_SEL0   (0x0u)
#define CM_DPLL_CM_MAC_CLKSEL_MII_CLK_SEL_SEL1   (0x1u)

/* CM_CPTS_RFT_CLKSEL */
#define CM_DPLL_CM_CPTS_RFT_CLKSEL_CLKSEL   (0x00000001u)
#define CM_DPLL_CM_CPTS_RFT_CLKSEL_CLKSEL_SHIFT   (0x00000000u)
#define CM_DPLL_CM_CPTS_RFT_CLKSEL_CLKSEL_SEL1   (0x0u)
#define CM_DPLL_CM_CPTS_RFT_CLKSEL_CLKSEL_SEL2   (0x1u)


/* CLKSEL_GFX_FCLK */
#define CM_DPLL_CLKSEL_GFX_FCLK_CLKDIV_SEL_GFX_FCLK   (0x00000001u)
#define CM_DPLL_CLKSEL_GFX_FCLK_CLKDIV_SEL_GFX_FCLK_SHIFT   (0x00000000u)
#define CM_DPLL_CLKSEL_GFX_FCLK_CLKDIV_SEL_GFX_FCLK_DIV1   (0x0u)
#define CM_DPLL_CLKSEL_GFX_FCLK_CLKDIV_SEL_GFX_FCLK_DIV2   (0x1u)

#define CM_DPLL_CLKSEL_GFX_FCLK_CLKSEL_GFX_FCLK   (0x00000002u)
#define CM_DPLL_CLKSEL_GFX_FCLK_CLKSEL_GFX_FCLK_SHIFT   (0x00000001u)
#define CM_DPLL_CLKSEL_GFX_FCLK_CLKSEL_GFX_FCLK_SEL0   (0x0u)
#define CM_DPLL_CLKSEL_GFX_FCLK_CLKSEL_GFX_FCLK_SEL1   (0x1u)


/* CLKSEL_ICSS_OCP_CLK */
#define CM_DPLL_CLKSEL_ICSS_OCP_CLK_CLKSEL   (0x00000001u)
#define CM_DPLL_CLKSEL_ICSS_OCP_CLK_CLKSEL_SHIFT   (0x00000000u)
#define CM_DPLL_CLKSEL_ICSS_OCP_CLK_CLKSEL_SEL1   (0x0u)
#define CM_DPLL_CLKSEL_ICSS_OCP_CLK_CLKSEL_SEL2   (0x1u)


/* CLKSEL_LCDC_PIXEL_CLK */
#define CM_DPLL_CLKSEL_LCDC_PIXEL_CLK_CLKSEL   (0x00000003u)
#define CM_DPLL_CLKSEL_LCDC_PIXEL_CLK_CLKSEL_SHIFT   (0x00000000u)
#define CM_DPLL_CLKSEL_LCDC_PIXEL_CLK_CLKSEL_SEL1   (0x0u)
#define CM_DPLL_CLKSEL_LCDC_PIXEL_CLK_CLKSEL_SEL2   (0x1u)
#define CM_DPLL_CLKSEL_LCDC_PIXEL_CLK_CLKSEL_SEL3   (0x2u)
#define CM_DPLL_CLKSEL_LCDC_PIXEL_CLK_CLKSEL_SEL4   (0x3u)


/* CLKSEL_WDT1_CLK */
#define CM_DPLL_CLKSEL_WDT1_CLK_CLKSEL   (0x00000001u)
#define CM_DPLL_CLKSEL_WDT1_CLK_CLKSEL_SHIFT   (0x00000000u)
#define CM_DPLL_CLKSEL_WDT1_CLK_CLKSEL_SEL1   (0x0u)
#define CM_DPLL_CLKSEL_WDT1_CLK_CLKSEL_SEL2   (0x1u)


/* CLKSEL_GPIO0_DBCLK */
#define CM_DPLL_CLKSEL_GPIO0_DBCLK_CLKSEL   (0x00000003u)
#define CM_DPLL_CLKSEL_GPIO0_DBCLK_CLKSEL_SHIFT   (0x00000000u)
#define CM_DPLL_CLKSEL_GPIO0_DBCLK_CLKSEL_SEL1   (0x0u)
#define CM_DPLL_CLKSEL_GPIO0_DBCLK_CLKSEL_SEL2   (0x1u)
#define CM_DPLL_CLKSEL_GPIO0_DBCLK_CLKSEL_SEL3   (0x2u)

